comment:
  after_n_builds: 3

coverage:
  status:
    project:
      default:
        target: auto
    patch:
      default:
        target: auto

flag_management:
  default_rules:
    carryforward: true
  individual_flags:
    - name: linux
      paths:
        - src/
    - name: macos
      paths:
        - src/
    - name: windows
      paths:
        - src/
